import Head from "next/head";
import Image from "next/image";
import classNames from "classnames";

const styles = {
  flexCenter: "flex justify-center items-center",
  container: "min-h-screen px-2 flex-col",
  main: "pt-20 flex-grow flex-col",
  footer: "w-full h-24 border-t flex flex-shrink-0",
  footerLink: "flex-grow",
  titleLink: "text-blue-700 hover:underline focus:underline",
  title: "font-bold m-0 leading-tight text-6xl text-center",
  description: "leading-tight text-2xl my-6",
  code: "bg-gray-100 rounded p-3 text-lg font-mono",
  grid: "flex-wrap container mt-12 flex-col sm:flex-row",
  card: "m-4 p-6 text-left text-current hover:text-blue-500 focus:text-blue-500 border border-gray-300 hover:border-blue-500 focus:border-blue-500 rounded-lg transition-colors md:w-1/3",
  cardHeader: "font-bold mb-4 text-2xl leading-normal",
  cardParagraph: "m-0 text-xl leading-normal",
  logo: "h-4 ml-2",
};

export default function Home() {
  return (
    <div className={classNames(styles.container, styles.flexCenter)}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={classNames(styles.main, styles.flexCenter)}>
        <h1 className={styles.title}>
          Welcome to{" "}
          <a className={styles.titleLink} href="https://nextjs.org">
            Next.js!
          </a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={classNames(styles.grid, styles.flexCenter)}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2 className={styles.cardHeader}>Documentation &rarr;</h2>
            <p className={styles.cardParagraph}>
              Find in-depth information about Next.js features and API.
            </p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2 className={styles.cardHeader}>Learn &rarr;</h2>
            <p className={styles.cardParagraph}>
              Learn about Next.js in an interactive course with quizzes!
            </p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2 className={styles.cardHeader}>Examples &rarr;</h2>
            <p className={styles.cardParagraph}>
              Discover and deploy boilerplate example Next.js projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2 className={styles.cardHeader}>Deploy &rarr;</h2>
            <p className={styles.cardParagraph}>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={classNames(styles.footer, styles.flexCenter)}>
        <a
          className={classNames(styles.footerLink, styles.flexCenter)}
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
